CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240924031345_Initial') THEN
    CREATE TABLE bills (
        id uuid NOT NULL,
        description text NOT NULL,
        category text NOT NULL,
        status text NOT NULL,
        amount_due numeric(10,2) NOT NULL,
        amount_paid numeric(10,2),
        due_date timestamp(3) with time zone NOT NULL,
        payment_date timestamp(3) with time zone,
        created_at timestamp(3) with time zone NOT NULL,
        updated_at timestamp(3) with time zone,
        deleted_at timestamp(3) with time zone,
        CONSTRAINT "PK_bills" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240924031345_Initial') THEN
    CREATE TABLE roles (
        id text NOT NULL,
        name character varying(256),
        normalized_name character varying(256),
        concurrency_stamp text,
        CONSTRAINT "PK_roles" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240924031345_Initial') THEN
    CREATE TABLE users (
        id text NOT NULL,
        "FirstName" text NOT NULL,
        "LastName" text NOT NULL,
        user_name character varying(256),
        normalized_user_name character varying(256),
        email character varying(256),
        normalized_email character varying(256),
        email_confirmed boolean NOT NULL,
        password_hash text,
        security_stamp text,
        concurrency_stamp text,
        phone_number text,
        phone_number_confirmed boolean NOT NULL,
        two_factor_enabled boolean NOT NULL,
        lockout_end timestamp with time zone,
        lockout_enabled boolean NOT NULL,
        access_failed_count integer NOT NULL,
        CONSTRAINT "PK_users" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240924031345_Initial') THEN
    CREATE TABLE role_claims (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        role_id text NOT NULL,
        claim_type text,
        claim_value text,
        CONSTRAINT "PK_role_claims" PRIMARY KEY (id),
        CONSTRAINT "FK_role_claims_roles_role_id" FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240924031345_Initial') THEN
    CREATE TABLE user_claims (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        user_id text NOT NULL,
        claim_type text,
        claim_value text,
        CONSTRAINT "PK_user_claims" PRIMARY KEY (id),
        CONSTRAINT "FK_user_claims_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240924031345_Initial') THEN
    CREATE TABLE user_logins (
        login_provider text NOT NULL,
        provider_key text NOT NULL,
        provider_display_name text,
        user_id text NOT NULL,
        CONSTRAINT "PK_user_logins" PRIMARY KEY (login_provider, provider_key),
        CONSTRAINT "FK_user_logins_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240924031345_Initial') THEN
    CREATE TABLE user_roles (
        user_id text NOT NULL,
        role_id text NOT NULL,
        CONSTRAINT "PK_user_roles" PRIMARY KEY (user_id, role_id),
        CONSTRAINT "FK_user_roles_roles_role_id" FOREIGN KEY (role_id) REFERENCES roles (id) ON DELETE CASCADE,
        CONSTRAINT "FK_user_roles_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240924031345_Initial') THEN
    CREATE TABLE user_tokens (
        user_id text NOT NULL,
        login_provider text NOT NULL,
        name text NOT NULL,
        value text,
        CONSTRAINT "PK_user_tokens" PRIMARY KEY (user_id, login_provider, name),
        CONSTRAINT "FK_user_tokens_users_user_id" FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240924031345_Initial') THEN
    CREATE INDEX "IX_role_claims_role_id" ON role_claims (role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240924031345_Initial') THEN
    CREATE UNIQUE INDEX "RoleNameIndex" ON roles (normalized_name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240924031345_Initial') THEN
    CREATE INDEX "IX_user_claims_user_id" ON user_claims (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240924031345_Initial') THEN
    CREATE INDEX "IX_user_logins_user_id" ON user_logins (user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240924031345_Initial') THEN
    CREATE INDEX "IX_user_roles_role_id" ON user_roles (role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240924031345_Initial') THEN
    CREATE INDEX "EmailIndex" ON users (normalized_email);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240924031345_Initial') THEN
    CREATE UNIQUE INDEX "UserNameIndex" ON users (normalized_user_name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20240924031345_Initial') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20240924031345_Initial', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE role_claims DROP CONSTRAINT "FK_role_claims_roles_role_id";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE user_claims DROP CONSTRAINT "FK_user_claims_users_user_id";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE user_logins DROP CONSTRAINT "FK_user_logins_users_user_id";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE user_roles DROP CONSTRAINT "FK_user_roles_roles_role_id";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE user_roles DROP CONSTRAINT "FK_user_roles_users_user_id";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE user_tokens DROP CONSTRAINT "FK_user_tokens_users_user_id";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE bills DROP CONSTRAINT "PK_bills";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE users DROP CONSTRAINT "PK_users";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE user_tokens DROP CONSTRAINT "PK_user_tokens";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE user_roles DROP CONSTRAINT "PK_user_roles";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE user_logins DROP CONSTRAINT "PK_user_logins";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE user_claims DROP CONSTRAINT "PK_user_claims";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE roles DROP CONSTRAINT "PK_roles";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE role_claims DROP CONSTRAINT "PK_role_claims";
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE users RENAME TO asp_net_users;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE user_tokens RENAME TO asp_net_user_tokens;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE user_roles RENAME TO asp_net_user_roles;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE user_logins RENAME TO asp_net_user_logins;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE user_claims RENAME TO asp_net_user_claims;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE roles RENAME TO asp_net_roles;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE role_claims RENAME TO asp_net_role_claims;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE asp_net_users RENAME COLUMN "LastName" TO last_name;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE asp_net_users RENAME COLUMN "FirstName" TO first_name;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER INDEX "UserNameIndex" RENAME TO user_name_index;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER INDEX "EmailIndex" RENAME TO email_index;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER INDEX "IX_user_roles_role_id" RENAME TO ix_asp_net_user_roles_role_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER INDEX "IX_user_logins_user_id" RENAME TO ix_asp_net_user_logins_user_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER INDEX "IX_user_claims_user_id" RENAME TO ix_asp_net_user_claims_user_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER INDEX "RoleNameIndex" RENAME TO role_name_index;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER INDEX "IX_role_claims_role_id" RENAME TO ix_asp_net_role_claims_role_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE bills ADD organization_id uuid NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE asp_net_users ADD organization_id uuid;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE bills ADD CONSTRAINT pk_bills PRIMARY KEY (id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE asp_net_users ADD CONSTRAINT pk_asp_net_users PRIMARY KEY (id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE asp_net_user_tokens ADD CONSTRAINT pk_asp_net_user_tokens PRIMARY KEY (user_id, login_provider, name);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE asp_net_user_roles ADD CONSTRAINT pk_asp_net_user_roles PRIMARY KEY (user_id, role_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE asp_net_user_logins ADD CONSTRAINT pk_asp_net_user_logins PRIMARY KEY (login_provider, provider_key);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE asp_net_user_claims ADD CONSTRAINT pk_asp_net_user_claims PRIMARY KEY (id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE asp_net_roles ADD CONSTRAINT pk_asp_net_roles PRIMARY KEY (id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE asp_net_role_claims ADD CONSTRAINT pk_asp_net_role_claims PRIMARY KEY (id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    CREATE TABLE organizations (
        id uuid NOT NULL,
        name text NOT NULL,
        created_at timestamp(3) with time zone NOT NULL,
        updated_at timestamp(3) with time zone,
        deleted_at timestamp(3) with time zone,
        CONSTRAINT pk_organization PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    CREATE INDEX ix_bills_organization_id ON bills (organization_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    CREATE INDEX ix_asp_net_users_organization_id ON asp_net_users (organization_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE asp_net_role_claims ADD CONSTRAINT fk_asp_net_role_claims_asp_net_roles_role_id FOREIGN KEY (role_id) REFERENCES asp_net_roles (id) ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE asp_net_user_claims ADD CONSTRAINT fk_asp_net_user_claims_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE asp_net_user_logins ADD CONSTRAINT fk_asp_net_user_logins_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE asp_net_user_roles ADD CONSTRAINT fk_asp_net_user_roles_asp_net_roles_role_id FOREIGN KEY (role_id) REFERENCES asp_net_roles (id) ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE asp_net_user_roles ADD CONSTRAINT fk_asp_net_user_roles_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE asp_net_user_tokens ADD CONSTRAINT fk_asp_net_user_tokens_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE asp_net_users ADD CONSTRAINT fk_asp_net_users_organization_organization_id FOREIGN KEY (organization_id) REFERENCES organizations (id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    ALTER TABLE bills ADD CONSTRAINT fk_bills_organization_organization_id FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241015020708_AddOrganization') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20241015020708_AddOrganization', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241109015855_ChangeUserOrganizationRelationship') THEN
    ALTER TABLE asp_net_users DROP CONSTRAINT fk_asp_net_users_organization_organization_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241109015855_ChangeUserOrganizationRelationship') THEN
    ALTER TABLE bills DROP CONSTRAINT fk_bills_organization_organization_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241109015855_ChangeUserOrganizationRelationship') THEN
    ALTER TABLE organizations DROP CONSTRAINT pk_organization;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241109015855_ChangeUserOrganizationRelationship') THEN
    DROP INDEX ix_asp_net_users_organization_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241109015855_ChangeUserOrganizationRelationship') THEN
    ALTER TABLE asp_net_users DROP COLUMN organization_id;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241109015855_ChangeUserOrganizationRelationship') THEN
    ALTER TABLE organizations ADD CONSTRAINT pk_organizations PRIMARY KEY (id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241109015855_ChangeUserOrganizationRelationship') THEN
    CREATE TABLE organization_user (
        members_id text NOT NULL,
        organizations_id uuid NOT NULL,
        CONSTRAINT pk_organization_user PRIMARY KEY (members_id, organizations_id),
        CONSTRAINT fk_organization_user_asp_net_users_members_id FOREIGN KEY (members_id) REFERENCES asp_net_users (id) ON DELETE CASCADE,
        CONSTRAINT fk_organization_user_organizations_organizations_id FOREIGN KEY (organizations_id) REFERENCES organizations (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241109015855_ChangeUserOrganizationRelationship') THEN
    CREATE INDEX ix_organization_user_organizations_id ON organization_user (organizations_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241109015855_ChangeUserOrganizationRelationship') THEN
    ALTER TABLE bills ADD CONSTRAINT fk_bills_organizations_organization_id FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241109015855_ChangeUserOrganizationRelationship') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20241109015855_ChangeUserOrganizationRelationship', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241119232551_AddExpenses') THEN
    CREATE TABLE expenses (
        id uuid NOT NULL,
        description text NOT NULL,
        category text NOT NULL,
        amount numeric(10,2) NOT NULL,
        created_at timestamp(3) with time zone NOT NULL,
        updated_at timestamp(3) with time zone,
        deleted_at timestamp(3) with time zone,
        organization_id uuid NOT NULL,
        CONSTRAINT pk_expenses PRIMARY KEY (id),
        CONSTRAINT fk_expenses_organizations_organization_id FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241119232551_AddExpenses') THEN
    CREATE INDEX ix_expenses_organization_id ON expenses (organization_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20241119232551_AddExpenses') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20241119232551_AddExpenses', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250118023053_AddOrganizationInvite') THEN
    CREATE TABLE organization_invites (
        id uuid NOT NULL,
        organization_id uuid NOT NULL,
        created_at timestamp with time zone NOT NULL,
        expires_at timestamp with time zone NOT NULL,
        is_used boolean NOT NULL,
        CONSTRAINT pk_organization_invites PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250118023053_AddOrganizationInvite') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250118023053_AddOrganizationInvite', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250126211643_AddExpensesRelationshipsWithOrganizationAndUsers') THEN
    UPDATE organization_invites SET expires_at = TIMESTAMPTZ '-infinity' WHERE expires_at IS NULL;
    ALTER TABLE organization_invites ALTER COLUMN expires_at SET NOT NULL;
    ALTER TABLE organization_invites ALTER COLUMN expires_at SET DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250126211643_AddExpensesRelationshipsWithOrganizationAndUsers') THEN
    ALTER TABLE expenses ADD created_by_user_id text NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250126211643_AddExpensesRelationshipsWithOrganizationAndUsers') THEN
    CREATE INDEX ix_expenses_created_by_user_id ON expenses (created_by_user_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250126211643_AddExpensesRelationshipsWithOrganizationAndUsers') THEN
    ALTER TABLE expenses ADD CONSTRAINT fk_expenses_asp_net_users_created_by_user_id FOREIGN KEY (created_by_user_id) REFERENCES asp_net_users (id) ON DELETE RESTRICT;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250126211643_AddExpensesRelationshipsWithOrganizationAndUsers') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250126211643_AddExpensesRelationshipsWithOrganizationAndUsers', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250127005619_AddPropertiesToExpenses') THEN
    ALTER TABLE expenses ADD occurred_at timestamp with time zone NOT NULL DEFAULT TIMESTAMPTZ '-infinity';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250127005619_AddPropertiesToExpenses') THEN
    ALTER TABLE expenses ADD status integer NOT NULL DEFAULT 0;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250127005619_AddPropertiesToExpenses') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250127005619_AddPropertiesToExpenses', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250818004434_AddBillDocument') THEN
    CREATE TABLE bill_documents (
        id uuid NOT NULL,
        bill_id uuid NOT NULL,
        file_name text NOT NULL,
        original_file_name text NOT NULL,
        content_type text NOT NULL,
        file_size_in_bytes bigint NOT NULL,
        storage_path text NOT NULL,
        document_type integer NOT NULL,
        storage_provider integer NOT NULL,
        description text,
        file_hash text,
        uploaded_at timestamp with time zone NOT NULL,
        uploaded_by_user_id uuid,
        deleted_at timestamp with time zone,
        CONSTRAINT pk_bill_documents PRIMARY KEY (id),
        CONSTRAINT fk_bill_documents_bills_bill_id FOREIGN KEY (bill_id) REFERENCES bills (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250818004434_AddBillDocument') THEN
    CREATE INDEX ix_bill_documents_bill_id ON bill_documents (bill_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250818004434_AddBillDocument') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250818004434_AddBillDocument', '10.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250922000151_AddUserSettingsTable') THEN
    ALTER TABLE organizations ADD timezone_id character varying(150) NOT NULL DEFAULT '';
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250922000151_AddUserSettingsTable') THEN
    ALTER TABLE bills ALTER COLUMN due_date TYPE date;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250922000151_AddUserSettingsTable') THEN
    CREATE TABLE user_settings (
        user_id text NOT NULL,
        preferred_language character varying(5),
        timezone_id character varying(150),
        created_at timestamp with time zone NOT NULL,
        updated_at timestamp with time zone,
        deleted_at timestamp with time zone,
        CONSTRAINT "PK_user_settings" PRIMARY KEY (user_id),
        CONSTRAINT fk_user_settings_asp_net_users_user_id FOREIGN KEY (user_id) REFERENCES asp_net_users (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20250922000151_AddUserSettingsTable') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20250922000151_AddUserSettingsTable', '10.0.0');
    END IF;
END $EF$;
COMMIT;

